name: Test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    # No venv in CI - install directly
    - name: Install dependencies
      run: |
        pip install -r requirements-dev.txt
    
    - name: Run linting
      run: |
        ruff check .
        mypy src/
    
    - name: Run tests
      run: |
        pytest tests/ -v --cov=src --cov-report=xml
    
    - name: Check coverage
      run: |
        coverage report --fail-under=80